---
- block:
    - name: Instala Puppet Server no CentOS
      yum:
        name: puppetserver
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Instala Puppet agent no Ubuntu
      apt:
        name: puppetserver
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

  tags: server
