---
- block:
    - name: Instala Puppet agent no CentOS
      yum:
        name: puppet-agent
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Instala Puppet agent no Ubuntu
      apt:
        name: puppet-agent
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

  tags: agent
