---
- hosts: dexter
  vars: 
    - install: vim
    - remove: htop
  tasks:
    - yum:
        name: "{{ install }}" 
        state: present

    - yum:
        name: "{{ remove }}"
        state: absent
