---
# tasks file for pacotes
#
- include_vars: "{{ ansible_os_family }}.yml"

- name: Istala pacotes nos sistemas baseados em Debian
  apt:
    name: "{{ pacotes_debian }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Istala pacotes nos sistemas baseados em CentOS
  yum:
    name: "{{ pacotes_redhat }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
